version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    command: sh -c "pnpm run dev"
